# Generated by Django 2.0.7 on 2019-05-14 04:31

import Movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banner', verbose_name='轮播图')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=30, unique=True, verbose_name='电影名称')),
                ('presentation', models.TextField(max_length=300, verbose_name='内容介绍')),
                ('relese_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('click', models.IntegerField(default='0', verbose_name='点击率')),
                ('collect', models.IntegerField(default='0', verbose_name='收藏人数')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=Movies.models.movie.get_cover, verbose_name='封面')),
                ('video', models.FileField(blank=True, default='videos/default.mp4', max_length=200, upload_to=Movies.models.movie.get_movie, verbose_name='视频文件')),
            ],
            options={
                'verbose_name': '电影列表',
                'verbose_name_plural': '电影列表',
            },
        ),
        migrations.CreateModel(
            name='movies_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True, verbose_name='视频类型')),
            ],
            options={
                'verbose_name': '视频类型',
                'verbose_name_plural': '视频类型',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='Type',
            field=models.ManyToManyField(blank=True, related_name='movietype', to='Movies.movies_type', verbose_name='视频类型'),
        ),
    ]
