# Generated by Django 2.0.7 on 2020-02-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operation', '0002_history_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_operation',
            name='add_time',
            field=models.CharField(max_length=16, verbose_name='电影名称'),
        ),
    ]
