# Generated by Django 2.0.7 on 2020-01-20 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 16, 50, 0, 210674), verbose_name='发送时间'),
        ),
    ]
